apiVersion: v1
kind: ServiceAccount
metadata:
  # For more information about using Kubernetes service accounts see:
  # https://cloud.google.com/kubernetes-engine/docs/how-to/kubernetes-service-accounts
  name: ksa-cloud-sql # TODO(developer): replace this value.
# [END cloud_sql_postgres_java_gke_quickstart_sa]
